version: '3.8'
services:
  web:
    image: acounts
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
 #     - rabbitmq

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

 # rabbitmq:
    #image: rabbitmq:3-management
   # ports:
  #    - "5673:5672"
 #     - "15673:15672"
   
