version: '3.8'
services:
  post-web:
    image: posts
    ports:
      - 8004:8000  
    volumes:
      - .:/app
    depends_on:
      - db 
  db:
    image: postgres:latest
    restart: always    
    environment:
      POSTGRES_DB: posts_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s      
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
